baseURL: http://saya-rbt.github.io/
languageCode: en-us
title: Saya's website
theme: "PaperMod"

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: Saya's website
    description: "Where I just write about what I want."
    keywords: [Blog, Portfolio, Robotics, Computer Science, Code, Saya]
    author: Saya
    DateFormat: "01/02/2006"

    defaultTheme: auto # dark, light
    disableThemeToggle: false

    ShowReadingTime: true
    ShowShareButtons: false
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: true
    tocopen: false

    profileMode:
        enabled: true
        title: "Hi! I'm Saya." # optional default will be site title
        subtitle: "I'm a robotics and computer science engineer, looking for a PhD. in HRI. This website contains mostly write-ups from my projects, but also opinions, ideas and thoughts if I feel like it."
        imageUrl: "https://avatars.githubusercontent.com/u/11200228?v=4" # optional
        imageTitle: "Avatar" # optional
        imageWidth: 120 # custom size
        imageHeight: 120 # custom size
        buttons:
            - name: About
              url: "/about"
            - name: Posts
              url: "/posts"

    socialIcons: # optional
        - name: "GitHub"
          url: "https://github.com/saya-rbt"
        - name: "Email"
          url: "mailto:saya-rbt@protonmail.com"

menu:
    main:
        - identifier: about
          name: About
          url: /about
          weight: 10
        - identifier: posts
          name: Posts
          url: /posts
          weight: 20